# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('kivy.ini', '.')
        ('assets', 'assets'),
        ('64gua.png', '.'),
    ],
    hiddenimports=[
        'kivy',
        'kivy.core',
        'kivy.core.window',
        'kivy.core.image',
        'kivy.core.text',
        'kivy.uix',
        'kivy.uix.boxlayout',
        'kivy.uix.button',
        'kivy.uix.label',
        'kivy.uix.floatlayout',
        'kivy.uix.relativelayout',
        'kivy.uix.scrollview',
        'kivy.uix.gridlayout',
        'kivy.uix.spinner',
        'kivy.uix.textinput',
        'kivy.uix.togglebutton',
        'kivy.uix.popup',
        'kivy.uix.dropdown',
        'kivy.uix.image',
        'kivy.graphics',
        'kivy.graphics.texture',
        'kivy.graphics.vertex_instructions',
        'kivy.graphics.instructions',
        'kivy.graphics.fbo',
        'kivy.graphics.opengl',
        'kivy.properties',
        'kivy.lang',
        'kivy.clock',
        'kivy.config',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageTk',
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='kivy_luopan',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
